# Generated by Django 4.2 on 2023-05-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_reciepe_reciepe_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciepe',
            name='reciepe_view_count',
            field=models.IntegerField(),
        ),
    ]
