# Generated by Django 4.2 on 2023-05-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_rename_reciepe_view_count_reciepe_recipe_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciepe',
            name='recipe_view_count',
        ),
        migrations.AddField(
            model_name='reciepe',
            name='reciepe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
