# Generated by Django 4.2 on 2023-05-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_remove_reciepe_recipe_view_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciepe',
            name='reciepe_view_count',
        ),
        migrations.AddField(
            model_name='reciepe',
            name='reciepe_comment',
            field=models.TextField(default=1),
        ),
    ]
