# Generated by Django 4.2 on 2023-05-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0008_remove_reciepe_reciepe_view_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciepe',
            name='reciepe_comment',
            field=models.TextField(default='add some comment'),
        ),
    ]
