# Generated by Django 4.2 on 2023-05-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0009_alter_reciepe_reciepe_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciepe',
            name='reciepe_comment',
            field=models.TextField(verbose_name='add some comments'),
        ),
    ]
