# Generated by Django 4.2 on 2023-05-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_reciepe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciepe',
            name='reciepe_comment',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
