# Generated by Django 4.2 on 2023-05-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_reciepe_reciepe_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciepe',
            name='reciepe_image',
        ),
    ]
