# Generated by Django 4.2 on 2023-05-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_remove_reciepe_reciepe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciepe',
            name='reciepe_image',
            field=models.ImageField(blank=True, upload_to='Recieps'),
        ),
    ]
