# Generated by Django 4.2 on 2023-05-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_reciepe_reciepe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciepe',
            name='reciepe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
