# Generated by Django 4.2 on 2023-05-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0010_reportcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportcard',
            old_name='student_marks',
            new_name='student_ranks',
        ),
    ]
