# Generated by Django 4.2 on 2023-05-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0011_rename_student_marks_reportcard_student_ranks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_ranks', 'date_of_report_card')},
        ),
    ]
